"""
Project Euler - Problem 12: Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers. So the $7$ th triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$ Let us list the factors of the first seven triangle numbers: $$\begin{align}
\mathbf 1 &\colon 1\\
\mathbf 3 &\colon 1,3\\
\mathbf 6 &\colon 1,2,3,6\\
\mathbf{10} &\colon 1,2,5,10\\
\mathbf{15} &\colon 1,3,5,15\\
\mathbf{21} &\colon 1,3,7,21\\
\mathbf{28} &\colon 1,2,4,7,14,28
\end{align}$$ We can see that $28$ is the first triangle number to have over five divisors. What is the value of the first triangle number to have over five hundred divisors?
"""

import math

def count_divisors(n):
    count = 0
    for i in range(1, int(math.sqrt(n)) + 1):
        if n % i == 0:
            if n // i == i:
                count += 1
            else:
                count += 2
    return count

def solution():
    i = 1
    while True:
        triangle_number = i * (i + 1) // 2
        if count_divisors(triangle_number) > 500:
            return triangle_number
        i += 1

if __name__ == "__main__":
    print(solution())  # Answer: 76576500